site_name: TopoGen
site_url: https://networmix.github.io/TopoGen/
repo_url: https://github.com/networmix/TopoGen
edit_uri: edit/main/docs/
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.integrate
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences # <-- enables nested fences
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Installation: getting-started/installation.md
  - CLI Reference: reference/cli.md
plugins:
  - search
