name: docs
on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install '.[dev]'

      - name: Deploy documentation
        run: mkdocs gh-deploy --force --clean
